name: airbnb-insights
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.1
  - numpy=1.26
  - scipy=1.11
  - jupyter=1.0
  - jupyterlab=4.0
  - plotly=5.18
  - pip
  - pip:
    - ydata-profiling==4.6.0
    - openpyxl
    - nbformat
